#!/bin/bash
source my.conf

cd ${MYHADOOP_SRC_HOME}/myshell/logs/

LOG_DIR_NAME=log-`date +"%Y-%m-%d %H:%M:%S"`
echo "log name: ${LOG_DIR_NAME}"
mkdir "${LOG_DIR_NAME}"
cd "${LOG_DIR_NAME}"

scp hadoop@n01:~/hadoop/logs/yarn*.log ./
scp hadoop@n02:~/hadoop/logs/yarn*.log ./
scp hadoop@n03:~/hadoop/logs/yarn*.log ./
scp hadoop@n04:~/hadoop/logs/yarn*.log ./

